# -*- coding: utf-8 -*-
"""Project TBA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l6h3py4SG4ADy_fd6pFbL8LdZiyVLX_q
"""

import string

alphabet_list = list(string.ascii_lowercase)
state_list = ['q0', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 
              'p11', 'p12', 'p13', 'p14', 'p15', 'p16', 'p17', 'p18', 'p19', 'p20', 
              'p21', 'p22', 'p23', 'p24', 'p25', 'p26', 'q1', 'q2', 'q3', 'q4', 'q5', 
              'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q12', 'q13', 'q14', 'q15', 'q16',
              'q17', 'q18', 'q19', 'q20', 'q21', 'x1']
accepted_state = ['p6', 'p11', 'p15', 'p18', 'p23', 'p26', 'q8', 'q16', 'q13', 'q21']

transition_table = {}

for s in state_list:
    for a in alphabet_list:
        transition_table[(s, a)] = 'error'
    transition_table[(s, '#')] = 'error'
    transition_table[(s, ' ')] = 'error'

#cireng
transition_table[('q0', ' ')] = 'q0'
transition_table[('q0', 'c')] = 'p16'
transition_table[('p16', 'i')] = 'p19'
transition_table[('p19', 'r')] = 'p20'
transition_table[('p20', 'e')] = 'p21'
transition_table[('p21', 'n')] = 'p22'
transition_table[('p22', 'g')] = 'p23'
transition_table[('p23', '#')] = 'accept'
transition_table[('p23', ' ')] = 'x1'
transition_table[('x1', '#')] = 'accept'
transition_table[('x1', ' ')] = 'x1'
transition_table[('x1', 'n')] = 'p16'

#cimol
transition_table[('q0', ' ')] = 'q0'
transition_table[('q0', 'c')] = 'p16'
transition_table[('p16', 'i')] = 'p19'
transition_table[('p19', 'm')] = 'p24'
transition_table[('p24', 'o')] = 'p25'
transition_table[('p25', 'l')] = 'p26'
transition_table[('p26', '#')] = 'accept'
transition_table[('p26', ' ')] = 'x1'
transition_table[('x1', '#')] = 'accept'
transition_table[('x1', ' ')] = 'x1'
transition_table[('x1', 'n')] = 'p16'

#sapatu
transition_table[('q0', ' ')] = 'q0'
transition_table[('q0', 's')] = 'p1'
transition_table[('p1', 'a')] = 'p2'
transition_table[('p2', 'p')] = 'p3'
transition_table[('p3', 'a')] = 'p4'
transition_table[('p4', 't')] = 'p5'
transition_table[('p5', 'u')] = 'p6'
transition_table[('p6', '#')] = 'accept'
transition_table[('p6', ' ')] = 'x1'
transition_table[('x1', '#')] = 'accept'
transition_table[('x1', ' ')] = 'x1'
transition_table[('x1', 's')] = 'p1'

#ngangge
transition_table[('q0', ' ')] = 'q0'
transition_table[('q0', 'n')] = 'q1'
transition_table[('q1', 'g')] = 'q2'
transition_table[('q2', 'a')] = 'q3'
transition_table[('q3', 'n')] = 'q10'
transition_table[('q10', 'g')] = 'q11'
transition_table[('q11', 'g')] = 'q12'
transition_table[('q12', 'e')] = 'q13'
transition_table[('q13', '#')] = 'accept'
transition_table[('q13', ' ')] = 'x1'
transition_table[('x1', '#')] = 'accept'
transition_table[('x1', ' ')] = 'x1'
transition_table[('x1', 'n')] = 'q1'

#ngadamel
transition_table[('q0', ' ')] = 'q0'
transition_table[('q0', 'n')] = 'q1'
transition_table[('q1', 'g')] = 'q2'
transition_table[('q2', 'a')] = 'q3'
transition_table[('q3', 'd')] = 'q4'
transition_table[('q4', 'a')] = 'q5'
transition_table[('q5', 'm')] = 'q6'
transition_table[('q6', 'e')] = 'q7'
transition_table[('q7', 'l')] = 'q8'
transition_table[('q8', '#')] = 'accept'
transition_table[('q8', ' ')] = 'x1'
transition_table[('x1', '#')] = 'accept'
transition_table[('x1', ' ')] = 'x1'
transition_table[('x1', 'n')] = 'q1'

#nyandak
transition_table[('q0', ' ')] = 'q0'
transition_table[('q0', 'n')] = 'q1'
transition_table[('q1', 'y')] = 'q9'
transition_table[('q9', 'a')] = 'q17'
transition_table[('q17', 'n')] = 'q18'
transition_table[('q18', 'd')] = 'q14'
transition_table[('q14', 'a')] = 'q15'
transition_table[('q15', 'k')] = 'q16'
transition_table[('q16', '#')] = 'accept'
transition_table[('q16', ' ')] = 'x1'
transition_table[('x1', '#')] = 'accept'
transition_table[('x1', ' ')] = 'x1'
transition_table[('x1', 'n')] = 'q1'

#meser
transition_table[('q0', ' ')] = 'q0'
transition_table[('q0', 'm')] = 'q17'
transition_table[('q17', 'e')] = 'q18'
transition_table[('q18', 's')] = 'q19'
transition_table[('q19', 'e')] = 'q20'
transition_table[('q20', 'r')] = 'q21'
transition_table[('q21', '#')] = 'accept'
transition_table[('q21', ' ')] = 'x1'
transition_table[('x1', '#')] = 'accept'
transition_table[('x1', ' ')] = 'x1'
transition_table[('x1', 'm')] = 'q17'

#anjeun
transition_table[('q0', ' ')] = 'q0'
transition_table[('q0', 'a')] = 'p12'
transition_table[('p12', 'n')] = 'p7'
transition_table[('p7', 'j')] = 'p8'
transition_table[('p8', 'e')] = 'p9'
transition_table[('p9', 'u')] = 'p10'
transition_table[('p10', 'n')] = 'p11'
transition_table[('p11', '#')] = 'accept'
transition_table[('p11', ' ')] = 'x1'
transition_table[('x1', '#')] = 'accept'
transition_table[('x1', ' ')] = 'x1'
transition_table[('x1', 'a')] = 'p12'

#abdi
transition_table[('q0', ' ')] = 'q0'
transition_table[('q0', 'a')] = 'p12'
transition_table[('p12', 'b')] = 'p13'
transition_table[('p13', 'd')] = 'p14'
transition_table[('p14', 'i')] = 'p15'
transition_table[('p15', '#')] = 'accept'
transition_table[('p15', ' ')] = 'x1'
transition_table[('x1', '#')] = 'accept'
transition_table[('x1', ' ')] = 'x1'
transition_table[('x1', 'a')] = 'p12'

# cau
transition_table[('q0', ' ')] = 'q0'
transition_table[('q0', 'c')] = 'p16'
transition_table[('p16', 'a')] = 'p17'
transition_table[('p17', 'u')] = 'p18'
transition_table[('p18', '#')] = 'accept'
transition_table[('p18', ' ')] = 'x1'
transition_table[('x1', '#')] = 'accept'
transition_table[('x1', ' ')] = 'x1'
transition_table[('x1', 'c')] = 'p16'

sentence = input("Enter your sentence:")
input_string = sentence.lower() + '#' 

index = 0
state = 'q0'
current_token = ''
while state != 'accept':
    current_token += input_string[index]
    state = transition_table[(state, input_string[index])]

    if state in accepted_state :
        print(f"Current Token {current_token} is valid")
        current_token = ''
    if state == 'error':
        print(f"Error, Current Sentence {sentence} is not valid")
        current_token = ''
        break
    index += 1

if state == 'accept':
    print(f'Success, All token in this sentence: {sentence} is valid')